[package]
name = "aoc"
version = "0.1.0"
authors = ["knas"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8.0"
regex = "1.4.2"